services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claims_app
    working_dir: /app
    entrypoint: ["python", "-m", "src.main"]
    command: ["--input", "data/test"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./db:/app/db
    tty: true
    stdin_open: true

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claims_dashboard
    working_dir: /app
    entrypoint: ["streamlit", "run", "src/analytics/analyze_dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./db:/app/db
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - app
